#!/usr/bin/env bash
set -euo pipefail  # http://redsymbol.net/articles/unofficial-bash-strict-mode/

XCODE_BIN_DIR="`xcode-select -p`/usr/bin"
XCODE_GIT="$XCODE_BIN_DIR/xcode-git"
GIT="$XCODE_BIN_DIR/git"
GIT_URL="https://raw.githubusercontent.com/chrisdanford/BetterXcodeGitBlame/master/git"
GIT_TEMP="/tmp/git-wrapper"

if [ -f $XCODE_GIT ]; then
   echo "Looks like we're already installed. File "$XCODE_GIT" already exists. Halt!"
   echo ""
   echo "You can uninstall by executing:"
   echo "sudo mv -f $XCODE_GIT $GIT"
   exit 1
fi
curl --output "$GIT_TEMP" "$GIT_URL" > $GIT_TEMP
echo ''
echo "Location of the Xcode-packaged git: $XCODE_BIN_DIR"
echo ''
echo 'The contents of Xcode will be modified.'
echo 'You may be prompted for your password. "sudo" is necessary to continue.'
sudo -- mv "$GIT" "$XCODE_GIT"
sudo -- mv "$GIT_TEMP" "$GIT"
sudo -- chmod +x "$GIT"
echo 'All done!'
